//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_USUARIO
    {
        public int ID_LOG { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public int ID_USUARIO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
