//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.LOG_USUARIO = new HashSet<LOG_USUARIO>();
        }
    
        public int ID_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<LOG_USUARIO> LOG_USUARIO { get; set; }
    }
}
